### ISSUE TITLE
Add  deerma.humidifier.jsq support

### ISSUE THREAD

**Issue by kuradi** [syssi/xiaomi_airpurifier#114]
`ERROR (MainThread) [homeassistant.components.xiaomi_miio.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq

homeassistant 0.118.4
`

**Comment by syssi** [comment]
You could install this custom component via HACS. Your device is supported already.

**Comment by kuradi** [comment]
> You could install this custom component via HACS. Your device is supported already.

oh sry. thank you.
now when i'm trying to add via hacs i'm getting "unknown error occured" and logs:

`2020-12-02 00:20:49 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/config_flow.py", line 95, in async_step_gateway
    await connect_gateway_class.async_connect_gateway(self.host, token)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/gateway.py", line 42, in async_connect_gateway
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/gateway.py", line 288, in discover_devices
    dev_info = SubDeviceInfo(*devices_raw[x : x + 5])
TypeError: __init__() missing 4 required positional arguments: 'type_id', 'unknown', 'unknown2', and 'fw_ver'

please advise`

**Comment by kuradi** [comment]
> You could install this custom component via HACS. Your device is supported already.

thank you. 
added component to custom components and also added configuration.yaml:

`fan:
  - platform: xiaomi_miio_airpurifier
    host: ***.***.***.***
    token: ***
    model: deerma.humidifier.jsq`

and i got this error. 

2020-12-02 21:16:53 ERROR (MainThread) [homeassistant.config] Platform error: fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 823, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 7, in <module>
    from miio import (  # pylint: disable=import-error
ImportError: cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)

**Comment by syssi** [comment]
You can find a workaround here: https://github.com/syssi/xiaomi_airpurifier/issues/98#issuecomment-733834983
