### ISSUE TITLE
ZNJSQ01DEM (deerma.humidifier.jsq) Not working

### ISSUE THREAD

**Issue by digitalsteezdesign** [syssi/xiaomi_airpurifier#119]
Can't seem to make this show in HA. Am i missing something?
My configuration.yaml
fan:
  - platform: xiaomi_miio_airpurifier
    name: Mi Smart Antibacterial Humidifier
    model: deerma.humidifier.jsq
    host: 192.168.1.183
    token: xxxxxx

**Comment by delicon** [comment]
I was writing this at the same time.

Here is more info aboout the product
Product: Mi Smart Antibacterial Humidifier
Model: ZNJSQ01DEM (SKV4140GL)

`[homeassistant.components.xiaomi_miio.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq`

**Comment by syssi** [comment]
Did you install this custom component via HACS? I own the same device and it's working / supported since 0.6.2:

```

fan:
  - platform: xiaomi_miio_airpurifier
    name: Air Humidifier
    host: !secret xiaomi_airhumidifier_host
    token: !secret xiaomi_airhumidifier_token
    model: deerma.humidifier.jsq
```

**Comment by delicon** [comment]
Yes, I've installed via HACS, it's version 0.6.2

This is my config:

```
fan:
  - platform: xiaomi_miio
    host: !secret air_purifier_ip
    token: !secret air_purifier_token
    name: Air Purifier

  - platform: xiaomi_miio_airpurifier
    name: Air Humidifier
    host: !secret air_humidifier_ip
    token: !secret air_humidifier_token
    model: deerma.humidifier.jsq
```
I can't validate the config.
After restart I got this errors:

```
2020-12-09 16:16:13 WARNING (MainThread) [homeassistant.setup] Setup of default_config is taking over 10 seconds.
2020-12-09 16:17:03 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: default_config
2020-12-09 16:17:31 ERROR (MainThread) [homeassistant.config] Platform error: fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 823, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 7, in <module>
    from miio import (  # pylint: disable=import-error
ImportError: cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)
```

**Comment by syssi** [comment]
This workaround is required as soon you don't use HA 1.0 which will be released on 13. december: https://github.com/syssi/xiaomi_airpurifier/issues/98

**Comment by delicon** [comment]
Thanks, it's working with the workaround.

**Comment by delicon** [comment]
One more question.
Can it be used as humidifier instead of fan integration?

**Comment by syssi** [comment]
It needs to be implemented first. You could monitor this issue meanwhile: https://github.com/syssi/xiaomi_airpurifier/issues/77

**Comment by digitalsteezdesign** [comment]
> Did you install this custom component via HACS? I own the same device and it's working / supported since 0.6.2:
> 
> ```
> 
> fan:
>   - platform: xiaomi_miio_airpurifier
>     name: Air Humidifier
>     host: !secret xiaomi_airhumidifier_host
>     token: !secret xiaomi_airhumidifier_token
>     model: deerma.humidifier.jsq
> ```

Hey there. Yeah this is how it is implemented.
fan:
  - platform: xiaomi_miio_airpurifier
    name: Mi Smart Antibacterial Humidifier
    model: deerma.humidifier.jsq
    host: 192.168.1.xxx
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Do i have to use your method with !secret for token and host?
