### ISSUE TITLE
dmaker.p9 bug

### ISSUE THREAD

**Issue by maximatchev** [syssi/xiaomi_airpurifier#120]
There is another error at Homeassistant 2020.12.0 with my dmaker.p9:

```
Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:2285
Integration: Вентилятор (documentation, issues)
First occurred: 1:33:15 (1 occurrences)
Last logged: 1:33:15

xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 2285, in async_update
    self._natural_mode = state.mode == FanOperationMode.Nature
  File "/usr/local/lib/python3.8/site-packages/miio/fan_miot.py", line 106, in mode
    return OperationMode[OperationModeMiot(self.data["mode"]).name]
  File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
    raise ve_exc
ValueError: 2 is not a valid OperationModeMiot
```

_Originally posted by @maximatchev in https://github.com/syssi/xiaomi_airpurifier/issues/86#issuecomment-744756296_

**Comment by myron412** [comment]
Hello, I also appear the same problem.
- [Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:1112
Integration: 风扇 (documentation, issues)
First occurred: 上午4:47:19 (1 occurrences)
Last logged: 上午4:47:19

xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1504, in async_update
    {
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1505, in <dictcomp>
    key: self._extract_value_from_attribute(state, value)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1112, in _extract_value_from_attribute
    value = getattr(state, attribute)
  File "/usr/local/lib/python3.8/site-packages/miio/airhumidifier_mjjsq.py", line 73, in mode
    return OperationMode(self.data["Humidifier_Gear"])
  File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
    raise ve_exc
ValueError: 5 is not a valid OperationMode ] 


version: 2020.12.0
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.79-v7l
arch: armv7l

**Comment by syssi** [comment]
@myron412 What's the model name of your device? It doesn't look like a fan.

**Comment by myron412** [comment]
> @myron412 What's the model name of your device? It doesn't look like a fan.

In fact, it's a humidifier, and the entity defines it as a fan

**Comment by syssi** [comment]
This issue is about the fan p8. This is the cause why I'm asking. I will try to reproduce the issue.

**Comment by myron412** [comment]
@syssi Updated to 12.1 after the problem solved. I guess is 12.0 version of the BUG.Thanks again for your reply to my issue.

**Comment by syssi** [comment]
This is strange because the hotfix release doesn't contain any regarding changes: https://www.home-assistant.io/blog/2020/12/13/release-202012/#release-2020121---december-16

**Comment by myron412** [comment]
Maybe the cache was cleaned up when the update occurred.And I may have overlooked this

**Comment by syssi** [comment]
@maximatchev Did you solve the issue? It looks like it's temporary.

**Comment by maximatchev** [comment]
I haven't tested till now.
So, it works
![image](https://user-images.githubusercontent.com/66755316/103160345-d49b5f80-47e4-11eb-8080-a8ae03367d9a.png)
Thank you

**Comment by maximatchev** [comment]
Hi, @syssi 
I have same error again ((

```
Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:2285
Integration: Вентилятор (documentation, issues)
First occurred: 2:55:54 (1 occurrences)
Last logged: 2:55:54

xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 2285, in async_update
    self._natural_mode = state.mode == FanOperationMode.Nature
  File "/usr/local/lib/python3.8/site-packages/miio/fan_miot.py", line 106, in mode
    return OperationMode[OperationModeMiot(self.data["mode"]).name]
  File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
    raise ve_exc
ValueError: 2 is not a valid OperationModeMiot
```

**Comment by syssi** [comment]
@maximatchev Could you provide list of your installed/used custom components?

**Comment by maximatchev** [comment]
![image](https://user-images.githubusercontent.com/66755316/103418531-2efb3e00-4ba0-11eb-9e0c-e3322c500a57.png)


![image](https://user-images.githubusercontent.com/66755316/103418708-e55f2300-4ba0-11eb-8dfd-60023294920d.png)

**Comment by syssi** [comment]
@maximatchev It looks like `Xiaomi Miio Gateway` requires an old `python-miio` version. As soon as all custom components are requiring the same python-miio version (>= 0.5.4) this issue will be gone.

**Comment by maximatchev** [comment]
@syssi excuse me, but I don't understand.

I uninstalled all xiaomi integrations now. 
So I have only Xiaomi miio gateway integration and this airpurifier integration.

And I have this error.
```
Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:2288
Integration: Вентилятор (documentation, issues)
First occurred: 11:27:01 (1 occurrences)
Last logged: 11:27:01

xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 2288, in async_update
    self._natural_mode = state.mode == FanOperationMode.Nature
  File "/usr/local/lib/python3.8/site-packages/miio/fan_miot.py", line 106, in mode
    return OperationMode[OperationModeMiot(self.data["mode"]).name]
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 2 is not a valid OperationModeMiot
```
I have no custom components with miio integration else

**Comment by maximatchev** [comment]
updated fan plugin in mi home application.... It works again
