### ISSUE TITLE
deerma.humidifier.jsq1 ValueError: 5 is not a valid OperationMode

### ISSUE THREAD

**Issue by foreignerby** [syssi/xiaomi_airpurifier#163]
Hi @syssi 

I mentioned my issue before, but I didn't get any response from you.

Sometimes my deerma.humidifier.jsq1 disappears from HA and I got an error in the logs(will be provided below).
It seems that my humidifier transmits some kind of parameter that integration cannot handle.
Could you please check it.

```
2021-04-06 07:26:37 ERROR (MainThread) [homeassistant.helpers.entity] Update for fan.xiaomi_air_humidifier fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1508, in async_update
    {
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1509, in <dictcomp>
    key: self._extract_value_from_attribute(state, value)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1116, in _extract_value_from_attribute
    value = getattr(state, attribute)
  File "/usr/local/lib/python3.8/site-packages/miio/airhumidifier_mjjsq.py", line 73, in mode
    return OperationMode(self.data["Humidifier_Gear"])
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 5 is not a valid OperationMode
```

**Comment by syssi** [comment]
Do you know the meaning of `OperationMode: 5`? How it's called at the Mi Home App?

**Comment by foreignerby** [comment]
I have no ideas about it. 
Maybe it "over wet protection". Because when this issue happened, the humidifier sets its speed on "low".
I never switched this mode on, but sometimes it appears as on. I don't know what makes it turn on.
Attaching the screenshot from MiHome
![Screenshot_20210410-154730_Mi Home](https://user-images.githubusercontent.com/80088469/114270335-7a7d7d80-9a14-11eb-93cb-b62604cdb782.jpg)

**Comment by syssi** [comment]
Operation mode 5 is the "over wet protection". If the Mi Home app detects the "operation mode 5" it changes the operation mode to "low" to protect the device.

**Comment by syssi** [comment]
This PR will fix the issue in future: https://github.com/rytilahti/python-miio/pull/1010

**Comment by foreignerby** [comment]
Am I understand right that you will release an update to your integration soon and this will be fixed?

**Comment by syssi** [comment]
Please update the custom component as soon this issue is closed. (Will take some weeks)
