### ISSUE TITLE
zhimi.airpurifier.ma4: The preset_mode Fan is not a valid preset_mode: ['Auto', 'Silent', 'Favorite']

### ISSUE THREAD

**Issue by andrew-yu** [syssi/xiaomi_airpurifier#176]
Got error message for my Air Purifier 3 - The preset_mode Fan is not a valid preset_mode: ['Auto', 'Silent', 'Favorite'].
'Fan' mode missing.

**Comment by syssi** [comment]
You tried to set the preset_mode "Fan" which isn't available. This is fine. Please use `Auto`, `Silent` or `Favorite` instead. What did you expect to happen?

**Comment by andrew-yu** [comment]
Hi, syssi, I expected that I can use all modes for Air Purifier 3/3H (2019) (zhimi.airpurifier.ma4/zhimi.airpurifier.mb3) - Preset modes (auto, silent, favorite, fan) - this is from docs of this component.

**Comment by syssi** [comment]
You are totally right. This is a bug. I wasn't aware of this special mode anymore.

**Comment by syssi** [comment]
@andrew-yu Do you use this custom component or the official version of the HA core? This custom component should support the operation mode `Fan`.

**Comment by andrew-yu** [comment]
I use custom component:

```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Mi Air Purifier 3
    host: 192.168.10.6
    token: xxx
    model: zhimi.airpurifier.ma4
```


my logs:
```
2021-04-20 22:36:24 ERROR (MainThread) [homeassistant.components.automation.air_purifier_mode_change] While executing automation automation.air_purifier_mode_change
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 500, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1200, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 321, in async_set_preset_mode
    self._valid_preset_mode_or_raise(preset_mode)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 328, in _valid_preset_mode_or_raise
    raise NotValidPresetModeError(
homeassistant.components.fan.NotValidPresetModeError: The preset_mode Fan is not a valid preset_mode: ['Auto', 'Silent', 'Favorite']
```

**Comment by syssi** [comment]
Could you try to call the service from the developer tools and provide the stack trace again? At the stack trace above no `xiaomi_miio_airpurifier` file is involved. This is a bit curious.

**Comment by syssi** [comment]
@andrew-yu ping.

**Comment by andrew-yu** [comment]
Give me another few, days for testing, please.

**Comment by andrew-yu** [comment]
After switching to xiaomi_miio_airpurifier integration i forget to remove purifier from xiaomi_miio (with new setup via gui).

Thank you for your great integration, syssi!
