### ISSUE TITLE
Add zhimi.airpurifier.za1 support

### ISSUE THREAD

**Issue by orionowy** [syssi/xiaomi_airpurifier#181]
### Request Smartmi zhimi.airpurifer.za1 - Air Purifier support 
[](https://www.smartmiglobal.com/collections/air-purifier/products/smartmi-air-purifier
)

**Xiaomi App Detalis details:**

```
ID: 393002509
IP: 192.168.0.xx
MODEL: zhimi.airpurifer.za1
```

**Current config:**

```
  - platform: xiaomi_miio_airpurifier
    name: Smartmi Air Purifer
    host: 192.168.0.XX
    token: e42bxxxxxxxxxxxxxxxxxxx2502
    model: zhimi.airpurifier.mb3
```

**Current states:**

```
preset_modes:
  - Auto
  - Silent
  - Favorite
  - Fan
preset_mode: null
model: zhimi.airpurifier.mb3
temperature: 22.8
humidity: 49
aqi: 19
mode: 0
filter_hours_used: 5
filter_life_remaining: 99
favorite_level: 14
child_lock: false
led: null
motor_speed: null
average_aqi: 31
purify_volume: 126
use_time: 37986
buzzer: true
led_brightness: 0
filter_rfid_product_id: '31:33:0:0'
filter_rfid_tag: '81:70:1e:aa:ca:71:4'
filter_type: regular
fan_level: null
friendly_name: Smartmi Air Purifer
supported_features: 8
```

![image](https://user-images.githubusercontent.com/52465748/116570841-da2bc200-a90a-11eb-9cca-97d64243f2e9.png)

**Comment by syssi** [comment]
Is my interpretation correct: The `zhimi.airpurifer.za1` is 100% feature compatible to the `zhimi.airpurifier.mb3`. If not: What's missing?

**Comment by syssi** [comment]
Could you provide some specs (product name, model no, specs) of your device? I would like to extend the list of supported devices as soon the device support is merged: https://github.com/syssi/xiaomi_airpurifier/pull/183

**Comment by orionowy** [comment]
Thank you for your response:

Some things are compatible with zhimi.airpurifier.mb3, but some functionalities are missing:
- the device status does not work (the device cannot be turned on and off)
- led not working (led: null)
- motor speed is not working (led: null
- fan level does not show value, probably no fan mode (fan_level: null)
- other preset_modes (Auto, Night, Favorite)
- mode atributte not show value (mode: 0)
- TVOC sensor status is not displayed

**Comment by holygrolli** [comment]
Did it work for you? I can see values but I cannot switch on or off through this integration

**Comment by pphomesmart** [comment]
> 
> 
> Did it work for you? I can see values but I cannot switch on or off through this integration

Got the same issue, the sensors are displaying the data (temperature, humidity etc.) but I'm unable to turn it on or off.

Additionally I'm getting error after leaving zhimi.airpurifier.za1 reference in configuration.yaml file, currently using zhimi.airpurifier.mb3 value:
![2021-07-10 23_03_31-Window](https://user-images.githubusercontent.com/74490966/126911555-4ded1597-7c6e-4359-b347-bf4d1fa83151.jpg)

**Comment by holygrolli** [comment]
what a coincidence today I had some time to play around a bit. I got it to work locally. I extended the `miio` package for ZA1 support and put it next to the custom_component. And it works :-)
You can just test it from this branch: https://github.com/holygrolli/xiaomi_airpurifier/tree/local_smartmi

I have to find some time to check for the TVOC value, but everything else seems to work. And finally I need to cleanup and then create a merge request to `miio` and to this very repo here

**Comment by FabFaeb** [comment]
Unfortunately, the airpurifier.za1 is still not working for me in HA without using the local fix of @holygrolli .

Is there still a chance for the pull request to the official repos, some time in the future, Andreas? Would be very much appreciated by a lot of people I think!

**Comment by pniewiadowski** [comment]
I am trying to run @holygrolli local fix but I get below error:

```
This error originated from a custom integration.

Logger: homeassistant.config
Source: custom_components/xiaomi_miio_airpurifier/fan.py:8
Integration: xiaomi_miio_airpurifier (documentation, issues)
First occurred: 8:57:05 PM (2 occurrences)
Last logged: 8:57:05 PM

Platform error: fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 572, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 589, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 8, in <module>
    from miio import (  # pylint: disable=import-error
ImportError: cannot import name 'AirDogX5' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)
```
Do you know how to solve it? Maybe @FabFaeb can help?

**Comment by syssi** [comment]
Please update the custom component (`xiaomi_airpurifier`). Recent versions of the component doesn't access the AirDogX5 class anymore.

**Comment by pniewiadowski** [comment]
@syssi so it means I can not use @holygrolli local solution anymore?

**Comment by syssi** [comment]
The solution must be updated first. The fork isn't `python-miio` compatible anymore.

**Comment by Phreet** [comment]
@an0nfunc thanks for your update! Unfortunately it doesnt work for me for Smartmi Air Purifier. Installed your latest dev and configured via yaml.

> /usr/local/lib/python3.9/site-packages/miio/device.py:158
Found an unsupported model 'zhimi.airpurifier.za1' for class 'AirPurifierMiot'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

> /usr/local/lib/python3.9/site-packages/miio/miot_device.py:172
Unable to find mapping for zhimi.airpurifier.za1, falling back to zhimi.airpurifier.ma4

**Comment by an0nfunc** [comment]
@Phreet Did you use the local_smartmi branch?

**Comment by FabFaeb** [comment]
@an0nfunc would it be possible to create a PR with your updates back to this repo so that the zhimi.airpurifier.za1 could be supported by default?

**Comment by an0nfunc** [comment]
@FabFaeb As far as I understand, these changes would need to go to python-miio. https://github.com/rytilahti/python-miio/issues/1025 already requests support for the za1, but there seems to be no activity so far. I'll check later what exactly I would need to do to get it upstreamed.

**Comment by Phreet** [comment]
> @Phreet Did you use the `local_smartmi` branch?

You are so right. HACS didnt offer me branch selection - therefore it took your dev branch, not the `local_smartmi`. Right branch selected and voila - it works, thanks for your code,

**Comment by dameq1** [comment]
If someone will be interested I can share my fork of @holygrolli's branch. I'm using this purifier so I'm updating it when it is needed. I also fixed problems which oryginal @holygrolli's mod had, like no possibility to set favorite speed or change lcd brightness.

**Comment by nils-hde** [comment]
> If someone will be interested I will share my fork of @holygrolli's branch https://github.com/dameq1/xiaomi_airpurifier_fork. I'm using this purifier so I'm updating it when it is needed. I also fixed problems which oryginal @holygrolli's mod had, like no possibility to set favorite speed or change lcd brightness. I modified my version using default branch so it will work also from hacs.

Thanks, unfortunately this doesn't work for me either :/

**Comment by an0nfunc** [comment]
For anyone interested, I just submitted a PR to get the za1 supported by HA's `xiaomi_miio` integration: https://github.com/home-assistant/core/pull/80387
