### ISSUE TITLE
zhimi.airpurifier.sa2 doesn't work with 0.6.11

### ISSUE THREAD

**Issue by daxingplay** [syssi/xiaomi_airpurifier#191]
Got an error message:

```
xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 407, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 516, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1400, in async_update
    {
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1401, in <dictcomp>
    key: self._extract_value_from_attribute(state, value)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1250, in _extract_value_from_attribute
    value = getattr(state, attribute)
  File "/usr/local/lib/python3.8/site-packages/miio/airpurifier.py", line 154, in mode
    return OperationMode(self.data["mode"])
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'low' is not a valid OperationMode
```

Seems that zhimi.airpurifier.sa2 returned an OperationMode that `python-miio` currently not supported. Should I open an issue in that repo? How can I check how many OperationModes in this model?

**Comment by daxingplay** [comment]
I found that python-miio needs to add this OperationMode to make it work. So I opened a PR in that repo: https://github.com/rytilahti/python-miio/pull/1054 . So I will close this issue. Thanks for your great work again.
