### ISSUE TITLE
Error while trying to add Smartmi Standing Fan 3 (zhimi.fan.za5)

### ISSUE THREAD

**Issue by nitobosch** [syssi/xiaomi_airpurifier#196]
Logger: homeassistant.components.fan
Source: util/percentage.py:21
Integration: Ventilador (documentation, issues)
First occurred: 13:54:25 (2 occurrences)
Last logged: 13:54:25

Error adding entities for domain fan with platform xiaomi_miio_fan
Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 603, in state_attributes
    data[ATTR_SPEED] = self.speed
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 453, in speed
    percentage = self.percentage
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1155, in percentage
    return ordered_list_item_to_percentage(FAN_SPEEDS_1C, self._preset_mode)
  File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 21, in ordered_list_item_to_percentage
    raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
ValueError: The item "None"" is not in "['Level 1', 'Level 2', 'Level 3']"

**Comment by syssi** [comment]
It looks like you are using `xiaomi_fan` to interface your fan. I've updated the `xiaomi_fan` component. The ZA5 should be supported now.
