### ISSUE TITLE
not working after updating HA

### ISSUE THREAD

**Issue by mcdull** [syssi/xiaomi_airpurifier#203]
2021-08-28 03:59:46 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Binary entities updater loop started!
2021-08-28 03:59:46 ERROR (MainThread) [homeassistant.components.climate] xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/config/custom_components/xiaomi_miio_airpurifier/climate.py", line 435, in async_update
state = await self.hass.async_add_executor_job(self._device.status)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/miio/airdehumidifier.py", line 201, in status
if self.device_info is None:
AttributeError: 'AirDehumidifier' object has no attribute 'device_info'

**Comment by syssi** [comment]
Duplicate #206.
