### ISSUE TITLE
Add HA core 2022.3.0 compatibility

### ISSUE THREAD

**Issue by timconinx** [syssi/xiaomi_airpurifier#253]
Logger: homeassistant.config
Source: custom_components/xiaomi_miio_airpurifier/fan.py:67
Integration: xiaomi_miio_airpurifier (documentation, issues)
First occurred: 8:52:32 PM (1 occurrences)
Last logged: 8:52:32 PM

Platform error: fan
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 572, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 589, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miio_airpurifier/fan.py", line 67, in <module>
    from miio.fan import (  # pylint: disable=import-error, import-error
ModuleNotFoundError: No module named 'miio.fan'

There were no problems with this integration until the latest update

**Comment by syssi** [comment]
You mean the latest HA core update. Right?

**Comment by timconinx** [comment]
Yes, sorry if it was unclear

## System Health

version | core-2022.3.0
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.9.2
os_name | Linux
os_version | 5.10.0-9-amd64
arch | x86_64
timezone | Europe/Brussels

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.23.0
Stage | running
Available Repositories | 1066
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

**Comment by syssi** [comment]
This custom component must be updated slightly to be 2022.3 compatible. I will give it a try later the week!
