### ISSUE TITLE
Bug in 2022.3.3

### ISSUE THREAD

**Issue by RaulVKoNe** [syssi/xiaomi_airpurifier#262]
Logger: homeassistant.config
Source: custom_components/xiaomi_miio_airpurifier/fan.py:8
Integration: xiaomi_miio_airpurifier ([documentation](https://github.com/syssi/xiaomi_airpurifier), [issues](https://github.com/syssi/xiaomi_airpurifier/issues))
First occurred: 09:38:33 (1 occurrences)
Last logged: 09:38:33

Platform error: fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 572, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 589, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 8, in <module>
    from miio import (  # pylint: disable=import-error
ImportError: cannot import name 'AirDogX5' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)

_------------_----------------------------------

Logger: homeassistant.helpers.event
Source: helpers/template.py:409
First occurred: 09:39:17 (6 occurrences)
Last logged: 09:39:17

Error while processing template: Template("{{ states.fan.xiaomi_air_humidifier.attributes.humidity }}")
Error while processing template: Template("{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}")
Error while processing template: Template("{{ states.fan.xiaomi_air_humidifier.attributes.no_water }}")
Error while processing template: Template("{{ states.fan.xiaomi_air_humidifier.attributes.water_tank_detached }}")
Error while processing template: Template("{{ states.fan.xiaomi_air_humidifier.attributes.preset_mode }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 407, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1814, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1840, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1831, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 523, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 409, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'

_----------------_----------------------

Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:167
Integration: Template ([documentation](https://www.home-assistant.io/integrations/template), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+template%22))
First occurred: 09:39:17 (6 occurrences)
Last logged: 09:39:17

TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.fan.xiaomi_air_humidifier.attributes.humidity }}")' for attribute '_attr_native_value' in entity 'sensor.xiaomi_air_humidifier_humidity'
TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}")' for attribute '_attr_native_value' in entity 'sensor.xiaomi_air_humidifier_target_humidity'
TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.fan.xiaomi_air_humidifier.attributes.no_water }}")' for attribute '_attr_native_value' in entity 'sensor.xiaomi_air_humidifier_no_water'
TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.fan.xiaomi_air_humidifier.attributes.water_tank_detached }}")' for attribute '_attr_native_value' in entity 'sensor.xiaomi_air_humidifier_water_tank_detached'
TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.fan.xiaomi_air_humidifier.attributes.preset_mode }}")' for attribute '_attr_native_value' in entity 'sensor.xiaomi_air_humidifier_preset_mode'

--------------------------------------

Logger: homeassistant.helpers.template
Source: helpers/template.py:1834
First occurred: 09:39:17 (60 occurrences)
Last logged: 09:47:17

Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.water_tank_detached }}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.preset_mode }}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.temperature }}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.humidity }}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'

**Comment by syssi** [comment]
This custom component isn't HA core 2022.3.3 compatible yet. To fix some issue of the official `xiaomi_miio` component the underlyling library was updated and has undergone a few breaking changes. I will update this custom component asap!

**Comment by RaulVKoNe** [comment]
> 

Thanks! I will return to the previous core or continue using a humidifier deerma

**Comment by syssi** [comment]
I've prepared a new release. Please give it a try.

**Comment by RaulVKoNe** [comment]
> 

Perfect!!!! Thanks!
