### ISSUE TITLE
xiaomi_miio_airpurifier: the fan is not created (2022.8)

### ISSUE THREAD

**Issue by ildar170975** [syssi/xiaomi_airpurifier#292]
### The problem

Starting from 2022.8  - this error in the log:

```
2022-08-03 17:36:03.887 ERROR (MainThread) [homeassistant.components.homeassistant] The system cannot restart because the configuration is not valid: Platform error fan.xiaomi_miio_airpurifier - No module named 'miio.airfresh'
2022-08-03 17:36:03.894 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140642317950912] The system cannot restart because the configuration is not valid: Platform error fan.xiaomi_miio_airpurifier - No module named 'miio.airfresh'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 746, in admin_handler
await result
File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 174, in async_handle_core_service
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error fan.xiaomi_miio_airpurifier - No module named 'miio.airfresh'
```

My `fan` entity is not created:
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: ...
    host: ...
    token: ...
    model: dmaker.airfresh.t2017
```

### What version of Home Assistant Core has the issue?

2022.8.0

### What was the last working version of Home Assistant Core?

2022.7.7

### What type of installation are you running?

Home Assistant Container

**Comment by Protoncek** [comment]
Yep, same error after updating HA to 2022.8: when validating in HA i get an error:
`Platform error fan.xiaomi_miio_airpurifier - No module named 'miio.airfresh'`
and i can't restart HA (not until i comment "fan" lines).

**Comment by gitrummy** [comment]
> Yep, same error after updating HA to 2022.8: when validating in HA i get an error: `Platform error fan.xiaomi_miio_airpurifier - No module named 'miio.airfresh'` and i can't restart HA (not until i comment "fan" lines).

Having this exact same issue also

**Comment by syssi** [comment]
I will prepare a fix at the weekend.

**Comment by syssi** [comment]
I would be happy if somebody could test these changes: https://github.com/syssi/xiaomi_airpurifier/pull/294

For example by copying/overwriting this file at the custom components folder: https://raw.githubusercontent.com/syssi/xiaomi_airpurifier/b7d55a489937862e1660660d0d657cfa88f705cc/custom_components/xiaomi_miio_airpurifier/fan.py

**Comment by ildar170975** [comment]
> I would be happy if somebody could test these changes:

Seems to work on my setup!
Thank you very much!!!!

**Comment by Protoncek** [comment]
Yea, works here too!! Thanks a million times!

**Comment by syssi** [comment]
I've prepared and published a new release. Please update using HACS.
