### ISSUE TITLE
MJXFJ-150-A1 / dmaker.airfresh.a1 error

### ISSUE THREAD

**Issue by olegskod** [syssi/xiaomi_airpurifier#348]
Logger: homeassistant.helpers.event
Source: helpers/event.py:293
First occurred: 22:42:35 (4 occurrences)
Last logged: 22:42:35

Error while dispatching event for fan.xiaomi_fresh_air_ventilator to <Job track state_changed event {'fan.xiaomi_fresh_air_ventilator'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ states.fan.xiaomi_fresh_air_ventilator.attributes.co2 }}) renders=6344>: <RenderInfo Template<template=({{ states.fan.xiaomi_fresh_air_ventilator.attributes.co2 }}) renders=6344> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'fan.xiaomi_fresh_air_ventilator'}) rate_limit=None has_time=False exception=None is_static=False>, Template<template=(mdi:molecule-co2) renders=3173>: <RenderInfo Template<template=(mdi:molecule-co2) renders=3173> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset() rate_limit=None has_time=False exception=None is_static=True>}>>>
Error while dispatching event for fan.xiaomi_fresh_air_ventilator to <Job track state_changed event {'fan.xiaomi_fresh_air_ventilator'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ states.fan.xiaomi_fresh_air_ventilator.attributes.pm25 }}) renders=6344>: <RenderInfo Template<template=({{ states.fan.xiaomi_fresh_air_ventilator.attributes.pm25 }}) renders=6344> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'fan.xiaomi_fresh_air_ventilator'}) rate_limit=None has_time=False exception=None is_static=False>, Template<template=(mdi:grain) renders=3173>: <RenderInfo Template<template=(mdi:grain) renders=3173> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset() rate_limit=None has_time=False exception=None is_static=True>}>>>
Error while dispatching event for fan.xiaomi_fresh_air_ventilator to <Job track state_changed event {'fan.xiaomi_fresh_air_ventilator'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ states.fan.xiaomi_fresh_air_ventilator.attributes.temperature }}) renders=6344>: <RenderInfo Template<template=({{ states.fan.xiaomi_fresh_air_ventilator.attributes.temperature }}) renders=6344> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'fan.xiaomi_fresh_air_ventilator'}) rate_limit=None has_time=False exception=None is_static=False>, Template<template=(mdi:thermometer) renders=3173>: <RenderInfo Template<template=(mdi:thermometer) renders=3173> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset() rate_limit=None has_time=False exception=None is_static=True>}>>>
Error while dispatching event for fan.xiaomi_fresh_air_ventilator to <Job track state_changed event {'fan.xiaomi_fresh_air_ventilator'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ states.fan.xiaomi_fresh_air_ventilator.attributes.dust_filter_life_remaining }}) renders=6344>: <RenderInfo Template<template=({{ states.fan.xiaomi_fresh_air_ventilator.attributes.dust_filter_life_remaining }}) renders=6344> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'fan.xiaomi_fresh_air_ventilator'}) rate_limit=None has_time=False exception=None is_static=False>, Template<template=(mdi:air-filter) renders=3173>: <RenderInfo Template<template=(mdi:air-filter) renders=3173> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset() rate_limit=None has_time=False exception=None is_static=True>}>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 616, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 619, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 293, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 659, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1211, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 659, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 429, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
    raise ValueError(
ValueError: Sensor sensor.xiaomi_fresh_air_ventilator_co2 has device class 'None', state class 'None' unit 'ppm' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)

Logger: homeassistant.components.automation.monitor_favorite_speed_and_update_slider
Source: helpers/script.py:1783
Integration: Автоматизация (documentation, issues)
First occurred: 22:42:35 (1 occurrences)
Last logged: 22:42:35

Monitor favorite speed and update slider: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'homeassistant.util.read_only_dict.ReadOnlyDict object' has no attribute 'favorite_speed'

Logger: homeassistant.components.automation.monitor_favorite_speed_and_update_slider
Source: components/automation/__init__.py:676
Integration: Автоматизация (documentation, issues)
First occurred: 22:42:35 (1 occurrences)
Last logged: 22:42:35

Error while executing automation automation.monitor_favorite_speed_and_update_slider: Error rendering data template: UndefinedError: 'homeassistant.util.read_only_dict.ReadOnlyDict object' has no attribute 'favorite_speed'

**Comment by rdeanar** [comment]
@olegskod I upgraded to the latest version of Home Assistant (2024.08.x), and the error with the integration is now gone.
