### ISSUE TITLE
No support  Airdog X7SM

### ISSUE THREAD

**Issue by GreshnikYa** [syssi/xiaomi_airpurifier#374]
Home Assistant Logs / 系统日志

Error while setting up xiaomi_miio_airpurifier platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1197, in async_setup_platform
device = XiaomiAirDog(name, air_purifier, model, unique_id, retries)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 3063, in init
AirDogOperationMode("Manual"),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/enum.py", line 757, in call
return cls.new(cls, value)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/enum.py", line 1171, in new
raise ve_exc
ValueError: 'Manual' is not a valid OperationMode

**Comment by syssi** [comment]
Do you know the model identifier (f.e. dmaker.fan.p18) of your device?

**Comment by GreshnikYa** [comment]
> Вы знаете идентификатор модели (например, dmaker.fan.p18) вашего устройства?

Sorry, I don’t quite understand what you’re talking about? where can I get it?

**Comment by GreshnikYa** [comment]
> Вы знаете идентификатор модели (например, dmaker.fan.p18) вашего устройства?
airdog.airpurifier.x7sm
