### ISSUE TITLE
Add support of zhimi.humidifier.cb1

### ISSUE THREAD

**Issue by koznov** [syssi/xiaomi_airpurifier#38]
Hello! 
Can you add support of zhimi.humidifier.cb1 - it is Smartmi Evaporative Humidifier:

akoznov@netbox:~/php-miio$ php miio-cli.php --ip 10.255.254.58 --token XXXXXXXXXX --info

Используем авто-формирование уникальных ID для команд из файла id.json
Информация об устройстве:
{"result":{"life":138354,"token":"061a870d52830625aaeea7aeb13a25ec","mac":"04:CF:8C:AA:DC:2B","fw_ver":"1.6.3","hw_ver":"MTK7697","uid":"155047449","model":"zhimi.humidifier.cb1","mcu_fw_ver":"1005","wifi_fw_ver":"20180702211408","config_type":"app","ap":{"rssi":-61,"ssid":"XXXXXXX","bssid":"XXXXXXXXXXX"},"netif":{"localIp":"10.255.254.58","mask":"255.255.255.0","gw":"10.255.254.1","gw_mac":"XXXXXX"},"mmfree":63968},"id":3}

Can i add some more data about it? If yes - what do you need in addition?
Thanks!

**Comment by syssi** [comment]
You could use the development version of Home Assistant. The CB1 support is already merged there: 

https://github.com/home-assistant/home-assistant/pull/27232

I will extend this "copy" soonish.

**Comment by koznov** [comment]
Can you give information how to change version to development? If throughout hasd.io supervisor - join beta - it is not working, I've updated and no changes.

**Comment by koznov** [comment]
@syssi , cant upgrade from 0.100.2  to 0.101.0.dev20191018 
```
19-10-18 04:41:17 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/dev.json
19-10-18 04:41:27 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.101.0.dev20191018
19-10-18 04:41:27 INFO (SyncWorker_18) [hassio.docker.interface] Update image homeassistant/raspberrypi3-homeassistant:0.100.2 to homeassistant/raspberrypi3-homeassistant:0.101.0.dev20191018
19-10-18 04:41:27 INFO (SyncWorker_18) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.101.0.dev20191018.
19-10-18 04:42:38 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
19-10-18 04:42:38 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
19-10-18 04:42:52 INFO (MainThread) [hassio.store] Load add-ons from store: 60 all - 0 new - 0 remove
19-10-18 04:56:03 INFO (SyncWorker_18) [hassio.docker.interface] Stop homeassistant application
19-10-18 04:56:26 INFO (SyncWorker_18) [hassio.docker.interface] Clean homeassistant application
19-10-18 04:56:36 INFO (SyncWorker_2) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.101.0.dev20191018
19-10-18 05:06:40 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home Assistant startup!
19-10-18 05:06:40 CRITICAL (MainThread) [hassio.homeassistant] HomeAssistant update fails -> rollback!
19-10-18 05:06:40 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.100.2
19-10-18 05:06:40 INFO (SyncWorker_13) [hassio.docker.interface] Update image homeassistant/raspberrypi3-homeassistant:0.101.0.dev20191018 to homeassistant/raspberrypi3-homeassistant:0.100.2
19-10-18 05:06:40 INFO (SyncWorker_13) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.100.2.
19-10-18 05:06:42 INFO (SyncWorker_13) [hassio.docker.interface] Stop homeassistant application
19-10-18 05:06:54 INFO (SyncWorker_13) [hassio.docker.interface] Clean homeassistant application
19-10-18 05:07:02 INFO (SyncWorker_18) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.100.2
19-10-18 05:08:12 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-10-18 05:08:12 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.100.2
19-10-18 05:08:14 INFO (SyncWorker_0) [hassio.docker.interface] Cleanup images: ['homeassistant/raspberrypi3-homeassistant:0.101.0.dev20191018']
```
Also there is Traceback in ha logs :

```
2019-10-18 09:07:31 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/updater/__init__.py", line 120, in check_new_version
    if StrictVersion(newest) > StrictVersion(current_version):
  File "/usr/local/lib/python3.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.7/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '0.101.0.dev20191018
```

**Comment by syssi** [comment]
The CB1 is supported officially since 0.101.
