### ISSUE TITLE
xiaomi_miio_airpurifier not work home assistant core 2024.12.5

### ISSUE THREAD

**Issue by runoka** [syssi/xiaomi_airpurifier#394]
I updated to
Home Assistant Core 2024.12.5
Home Assistant Supervisor 2024.12.0

And got the error
Configuration warnings
Platform error 'fan' from integration 'xiaomi_miio_airpurifier' - cannot import name 'Adapter' from 'construct' (unknown location)
Platform error 'fan' from integration 'xiaomi_miio_airpurifier' - cannot import name 'Adapter' from 'construct' (unknown location)
Platform error 'fan' from integration 'xiaomi_miio_airpurifier' - cannot import name 'Adapter' from 'construct' (unknown location)
Platform error 'fan' from integration 'xiaomi_miio_airpurifier' - cannot import name 'Adapter' from 'construct' (unknown location)

```
Detected blocking call to import_module with args ('custom_components.xiaomi_miio_airpurifier.fan',) in /usr/src/homeassistant/homeassistant/loader.py, line 1303: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration platform = await p_integration.integration.async_get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 1107, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1172, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")
```

version custom_component: xiaomi_miio_airpurifier 2024.8.0.0

**Comment by syssi** [comment]
This looks like a conflict with another custom component requiring `construct`. Which custom components do you use?
