### ISSUE TITLE
KeyError: 'motor1_speed' error

### ISSUE THREAD

**Issue by tyjtyj** [syssi/xiaomi_airpurifier#4]
Everything was fine if i comment out the line 191. 

home-assistant = 0.52.1 (on rpi3)
mirobo = 0.1.4

```
2017-09-03 08:34:38 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 235, in _step
    result = coro.send(value)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 210, in async_add_entity
    yield from entity.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/fan/xiaomi_airpurifier.py", line 191, in async_update
    ATTR_MOTOR_SPEED: state.motor_speed
  File "/srv/homeassistant/lib/python3.4/site-packages/mirobo/airpurifier.py", line 166, in motor_speed
    return self.data["motor1_speed"]
KeyError: 'motor1_speed'

```

**Comment by syssi** [comment]
The air purifier support of mirobo 0.1.4 is slightly broken. It's fixed in newer revisions because of

https://github.com/rytilahti/python-mirobo/pull/40

The custom component requires revision
```
REQUIREMENTS = ['https://github.com/rytilahti/python-mirobo/archive/'
                '168f5c0ff381b3b02cedd0917597195b3c521a20.zip#'
                'python-mirobo']
```
at least. I will resync all components based on mirobo to resolve the mixed dependency issues. A mirobo release > 0.1.4. is required.

**Comment by tyjtyj** [comment]
Awesome..... thanks for responding... 

Let just wait for mirobo stable release > 0.1.4.
