### ISSUE TITLE
xiaomi_miio_airpurifier: Error on device update! xiaomi humidifier 2

### ISSUE THREAD

**Issue by wisesokol** [syssi/xiaomi_airpurifier#42]
I have an error
xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1068, in async_update
    for key, value in self._available_attributes.items()
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1068, in <dictcomp>
    for key, value in self._available_attributes.items()
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 727, in _extract_value_from_attribute
    value = getattr(state, attribute)
AttributeError: 'AirHumidifierStatus' object has no attribute 'speed'

in configuration.yaml
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: 192.168.1.215
    token: 982de7b70xxxxxxxx7485765fab062
    model: zhimi.humidifier.ca1

**Comment by syssi** [comment]
Fixed. Please update the custom component or use the official one.
