### ISSUE TITLE
Error while setting up platform xiaomi_miio_airpurifier

### ISSUE THREAD

**Issue by anhnvme** [syssi/xiaomi_airpurifier#44]
Hello,

yesterday after install, it's working, but today, i need update other device and tried restart home asssistant, i got this error
i'm already tried remove folder and recreate folder xiaomi_miio_airpurifier
```
2019-12-14 11:30:21 ERROR (MainThread) [homeassistant.components.fan] Error while setting up platform xiaomi_miio_airpurifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 609, in async_setup_platform
    from miio import AirHumidifierMjjsq
ImportError: cannot import name 'AirHumidifierMjjsq' from 'miio' (/usr/local/lib/python3.7/site-packages/miio/__init__.py)
```

**Comment by syssi** [comment]
The most recent release of HA comes with python-miio 0.4.7. This custom component requires 0.4.8. To fix this issue you must use the development version of HA.

**Comment by anhnvme** [comment]
> The most recent release of HA comes with python-miio 0.4.7. This custom component requires 0.4.8. To fix this issue you must use the development version of HA.

Thanks you, i'm move to dev branch on docker and it's work
