### ISSUE TITLE
Xiaomi Mijia Smart Sterilization Humidifier (SCK0A45) error - Platform xiaomi_miio_airpurifier not ready yet. Retrying in 180 seconds.

### ISSUE THREAD

**Issue by cayco** [syssi/xiaomi_airpurifier#51]
I'm trying to connect with Xiaomi Mijia Smart Sterilization Humidifier (SCK0A45) Platform and get the error in logs: 
```xiaomi_miio_airpurifier not ready yet. Retrying in 180 seconds.```

My configuration looks like this:
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Nawilzacz
    host: 10.0.0.74
    token: 022938e31562f9036688c0f0e80de7b2
```

If I include ```    model: deerma.humidifier.mjjsq``` I get other error:

```
Got exception while fetching the state: No response from the device
10:16:36 – custom_components/xiaomi_miio_airpurifier/fan.py (ERROR) - wiadomość pojawiła się po raz pierwszy o godzinie 10:15:14 i powtarzała się 3 razy
Got error when receiving: timed out

10:16:36 – /usr/local/lib/python3.7/site-packages/miio/device.py (ERROR) - wiadomość pojawiła się po raz pierwszy o godzinie 10:15:14 i powtarzała się 3 razy
Update of fan.nawilzacz is taking over 10 seconds

10:16:26 – __main__.py (WARNING) - wiadomość pojawiła się po raz pierwszy o godzinie 10:15:55 i powtarzała się 2 razy
Header missing

10:16:12 – components/stream/worker.py (ERROR)
['Low', 'Medium', 'High', 'Humidity'] does not contain the speed setting off as its first element. Assuming that Low is equivalent to 'off'.

10:15:20 – homekit (WARNING)
Setup of fan platform xiaomi_miio_airpurifier is taking over 10 seconds.
10:15:02 – Wentylator (WARNING)
```

Manual `mirobo` command run in debug mode reports:
```
.env/bin/mirobo -d status
INFO:miio.vacuum_cli:Debug mode active
DEBUG:miio.vacuum_cli:Connecting to 10.0.0.74 with token cd2be39bd7274dfd36d7051cba9a5650
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x10\\/^\x00\x00\x02\x07' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('105c2f5e')
            ts = 1970-01-01 00:08:39
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.device:Discovered 105c2f5e with ts: 1970-01-01 00:08:39, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:10.0.0.74:54321 >>: {'id': 1, 'method': 'get_status', 'params': []}
DEBUG:miio.device:Retrying with incremented id, retries left: 3
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x10\\/^\x00\x00\x02\x0c' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('105c2f5e')
            ts = 1970-01-01 00:08:44
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.device:Discovered 105c2f5e with ts: 1970-01-01 00:08:44, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:10.0.0.74:54321 >>: {'id': 102, 'method': 'get_status', 'params': []}
DEBUG:miio.device:Retrying with incremented id, retries left: 2
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x10\\/^\x00\x00\x02\x11' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('105c2f5e')
            ts = 1970-01-01 00:08:49
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.device:Discovered 105c2f5e with ts: 1970-01-01 00:08:49, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:10.0.0.74:54321 >>: {'id': 203, 'method': 'get_status', 'params': []}
DEBUG:miio.device:Retrying with incremented id, retries left: 1
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x10\\/^\x00\x00\x02\x16' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('105c2f5e')
            ts = 1970-01-01 00:08:54
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.device:Discovered 105c2f5e with ts: 1970-01-01 00:08:54, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:10.0.0.74:54321 >>: {'id': 304, 'method': 'get_status', 'params': []}
ERROR:miio.device:Got error when receiving: timed out
DEBUG:miio.click_common:Exception: No response from the device
Traceback (most recent call last):
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/device.py", line 272, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/device.py", line 272, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/device.py", line 272, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/device.py", line 272, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/vacuum_cli.py", line 112, in status
    res = vac.status()
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/vacuum.py", line 176, in status
    return VacuumStatus(self.send("get_status")[0])
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/device.py", line 310, in send
    return self.send(command, parameters, retry_count - 1)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/device.py", line 310, in send
    return self.send(command, parameters, retry_count - 1)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/device.py", line 310, in send
    return self.send(command, parameters, retry_count - 1)
  File "/Users/krzysztofkajkowski/miio/.env/lib/python3.7/site-packages/miio/device.py", line 313, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
Error: No response from the device
```

In order to remedy the problem, I reset Mi Hub, which re-generated toke, reset humidifier (both button for 5s) and reconnected to Mi Home app (iOS 4.26.1). I can read token in Android Mi Home app 5.4.49 but for some reason, I cannot connect to the humidifier from there (I get extension cannot be initialized error). Everything works from iOS though.

**Comment by cayco** [comment]
Maybe it's some general issue: https://github.com/rytilahti/python-miio/issues/635

**Comment by cayco** [comment]
It's the same when using `miiocli`

```~/miio  .env/bin/miiocli -d airhumidifiermjjsq --ip 10.0.0.74 --token cd2be39bd7274dfd36d7051cba9a5650 info
INFO:miio.cli:Debug mode active
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x10\\/^\x00\x00\x12\x81' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('105c2f5e')
            ts = 1970-01-01 01:18:57
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.device:Discovered 105c2f5e with ts: 1970-01-01 01:18:57, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:10.0.0.74:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.device:Retrying with incremented id, retries left: 3
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x10\\/^\x00\x00\x12\x87' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('105c2f5e')
            ts = 1970-01-01 01:19:03
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
```
(...)

**Comment by syssi** [comment]
Do you know the procotol or model identifier of your device? This component supports some miIO device. The most recent protocol is called mIOT (take a look at the python-miio repo). It's possible your device talks mIOT.

**Comment by cayco** [comment]
Hi, if you ask for model name it's SCK0A45 (as I wrote in the issue name). 

Before writing bug description I looked on the python-miio and `miio-cli` command I used before was from that repo. That's why my second comment mentions `python-miio` repository and some other, similar bug...

**Comment by cayco** [comment]
It does work for the hub:
```
.env/bin/miiocli -d airhumidifiermjjsq --ip 10.0.0.138 --token cd2be39bd7274dfd36d7051cba9a5650 info
INFO:miio.cli:Debug mode active
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x07\xfd\x1e\xdb\x00\x00&\n' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('07fd1edb')
            ts = 1970-01-01 02:42:18
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' (total 16)
DEBUG:miio.device:Discovered 07fd1edb with ts: 1970-01-01 02:42:18, token: b'00000000000000000000000000000000'
DEBUG:miio.device:10.0.0.138:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.device:10.0.0.138:54321 (ts: 1970-01-01 02:42:18, id: 1) << {'result': {'life': 9738, 'cfg_time': 0, 'token': 'cd2be39bd7274dfd36d7051cba9a5650', 'mac': '04:CF:8C:B0:8E:09', 'fw_ver': '1.4.1_175', 'hw_ver': 'MW300', 'model': 'lumi.gateway.v3', 'mcu_fw_ver': '0220', 'wifi_fw_ver': 'SD878x-14.76.36.p84-702.1.0-WM', 'ap': {'rssi': -68, 'ssid': 'ABW-51n', 'bssid': 'E8:94:F6:EB:DB:88'}, 'netif': {'localIp': '10.0.0.138', 'mask': '255.255.255.0', 'gw': '10.0.0.1', 'gw_mac': 'E8:94:F6:EB:DB:88'}, 'mmfree': 176688, 'ot': 'otu', 'otu_stat': [350, 403, 533, 23, 467, 132], 'ott_stat': [0, 0, 0, 0]}, 'id': 1}
Model: lumi.gateway.v3
Hardware version: MW300
Firmware version: 1.4.1_175
Network: {'localIp': '10.0.0.138', 'mask': '255.255.255.0', 'gw': '10.0.0.1', 'gw_mac': 'E8:94:F6:EB:DB:88'}
AP: {'rssi': -68, 'ssid': 'ABW-51n', 'bssid': 'E8:94:F6:EB:DB:88'}
```

**Comment by cayco** [comment]
I reset the device, added it again and check the token using ios backup, described here: https://github.com/mediter/miio/blob/master/docs/ios-token-without-reset.md I used the token from the humidifier
```
sqlite> select ZNAME, ZTOKEN, ZMAC, ZLOCALIP from ZDevice;
Nawilżacz powietrza|3cc149ce8abe67aacacc3f99098cfaaed0e83cf364c232e8773805c5f52049060143db63ee66b0cdff9f69917680151e|50:EC:50:B2:8C:EE|10.0.0.74
```
and decoded in on the page: http://aes.online-domain-tools.com/

It works for other tokens (for example for the vacuum cleaner) but not for this.

**Comment by Smoky979** [comment]
did anyone add a humidifier to HA?

**Comment by cayco** [comment]
I have no luck so far

**Comment by zavisko** [comment]
hi everyone,

it works for me well, i have two of SCK0A45
the only issue is that im only able to turn them on or off or set the speed
im not able to set/change other things like target_humidity, buzzer or led - they are read only values
![2020-04-17_173713](https://user-images.githubusercontent.com/63862272/79586993-2aeec500-80d2-11ea-9a4d-f1a054104aeb.png)

here is my code from configuration.yaml:
```
sensor:
  - platform: template
    sensors:
      h_pbr:
        value_template: '{{ states.fan.hum_pbr.attributes.humidity }}'
      h_bbr:
        value_template: '{{ states.fan.hum_bbr.attributes.humidity }}'

fan:
  - platform: xiaomi_miio_airpurifier
    name: hum_pbr
    host: 192.168.3.152
    token: ...
  - platform: xiaomi_miio_airpurifier
    name: hum_bbr
    host: 192.168.3.153
    token: ...
```

**Comment by Smoky979** [comment]
> hi everyone,
> 
> it works for me well, i have two of SCK0A45
> the only issue is that im only able to turn them on or off or set the speed
> im not able to set/change other things like target_humidity, buzzer or led - they are read only values
> ![2020-04-17_173713](https://user-images.githubusercontent.com/63862272/79586993-2aeec500-80d2-11ea-9a4d-f1a054104aeb.png)
> 
> here is my code from configuration.yaml:
> 
> ```
> sensor:
>   - platform: template
>     sensors:
>       h_pbr:
>         value_template: '{{ states.fan.hum_pbr.attributes.humidity }}'
>       h_bbr:
>         value_template: '{{ states.fan.hum_bbr.attributes.humidity }}'
> 
> fan:
>   - platform: xiaomi_miio_airpurifier
>     name: hum_pbr
>     host: 192.168.3.152
>     token: ...
>   - platform: xiaomi_miio_airpurifier
>     name: hum_bbr
>     host: 192.168.3.153
>     token: ...
> ```


Super buddy, I'll go try to add.

**Comment by Smoky979** [comment]
> hi everyone,
> 
> it works for me well, i have two of SCK0A45
> the only issue is that im only able to turn them on or off or set the speed
> im not able to set/change other things like target_humidity, buzzer or led - they are read only values
> ![2020-04-17_173713](https://user-images.githubusercontent.com/63862272/79586993-2aeec500-80d2-11ea-9a4d-f1a054104aeb.png)
> 
> here is my code from configuration.yaml:
> 
> ```
> sensor:
>   - platform: template
>     sensors:
>       h_pbr:
>         value_template: '{{ states.fan.hum_pbr.attributes.humidity }}'
>       h_bbr:
>         value_template: '{{ states.fan.hum_bbr.attributes.humidity }}'
> 
> fan:
>   - platform: xiaomi_miio_airpurifier
>     name: hum_pbr
>     host: 192.168.3.152
>     token: ...
>   - platform: xiaomi_miio_airpurifier
>     name: hum_bbr
>     host: 192.168.3.153
>     token: ...
> ```


I didn’t succeed, please step by step what and how to do. Added your config to configuration.yaml with its ip and token, but the entity did not appear.

**Comment by zavisko** [comment]
> 
> I didn’t succeed, please step by step what and how to do. Added your config to configuration.yaml with its ip and token, but the entity did not appear.

nothing special,
- updated homeassistant, i'm now on version 0.108.4
- uploaded xiaomi_miio_airpurifier to custom_components folder
- added the mentioned entries to configuration.yaml

**Comment by Smoky979** [comment]
> * uploaded xiaomi_miio_airpurifier to custom_components folder
how to do it? do not quite understand.

**Comment by Smoky979** [comment]
> >
> * uploaded xiaomi_miio_airpurifier to custom_components folder


how to do it? do not quite understand.

**Comment by zavisko** [comment]
just downloaded these four files: https://github.com/syssi/xiaomi_airpurifier/tree/develop/custom_components/xiaomi_miio_airpurifier
![gitpic](https://user-images.githubusercontent.com/63862272/80317930-e9af9100-8806-11ea-9e30-bbca5039e90f.png)

and uploaded them to my custom_components/xiaomi_miio_airpurifier folder
![putty](https://user-images.githubusercontent.com/63862272/80317931-ecaa8180-8806-11ea-93af-7fb33fe0fa0e.png)

**Comment by Smoky979** [comment]
> just downloaded these four files: https://github.com/syssi/xiaomi_airpurifier/tree/develop/custom_components/xiaomi_miio_airpurifier
> ![gitpic](https://user-images.githubusercontent.com/63862272/80317930-e9af9100-8806-11ea-9e30-bbca5039e90f.png)
> 
> and uploaded them to my custom_components/xiaomi_miio_airpurifier folder
> ![putty](https://user-images.githubusercontent.com/63862272/80317931-ecaa8180-8806-11ea-93af-7fb33fe0fa0e.png)

https://github.com/syssi/xiaomi_airpurifier/issues/51#issuecomment-619614008

> just downloaded these four files: https://github.com/syssi/xiaomi_airpurifier/tree/develop/custom_components/xiaomi_miio_airpurifier
> ![gitpic](https://user-images.githubusercontent.com/63862272/80317930-e9af9100-8806-11ea-9e30-bbca5039e90f.png)
> 
> and uploaded them to my custom_components/xiaomi_miio_airpurifier folder
> ![putty](https://user-images.githubusercontent.com/63862272/80317931-ecaa8180-8806-11ea-93af-7fb33fe0fa0e.png)

https://github.com/syssi/xiaomi_airpurifier/issues/51#issuecomment-619614008

**Comment by Smoky979** [comment]
> just downloaded these four files: https://github.com/syssi/xiaomi_airpurifier/tree/develop/custom_components/xiaomi_miio_airpurifier
> ![gitpic](https://user-images.githubusercontent.com/63862272/80317930-e9af9100-8806-11ea-9e30-bbca5039e90f.png)
> 
> and uploaded them to my custom_components/xiaomi_miio_airpurifier folder
> ![putty](https://user-images.githubusercontent.com/63862272/80317931-ecaa8180-8806-11ea-93af-7fb33fe0fa0e.png)


I have sensors and fans placed in separate files in configuration.yaml there I did exactly the same as yours. By means of samba, I copied the files via the link to my custom_components / xiaomi_miio_airpurifier folder folder. Now, when I check the server configuration, there is an endless check. I can’t understand where the error is.

**Comment by syssi** [comment]
Closing this because of inactivity. The device is supported and should work of the box if a valid token is provided.
