### ISSUE TITLE
Deerma Huidifier Issue

### ISSUE THREAD

**Issue by benimotive** [syssi/xiaomi_airpurifier#54]
Hi , i'm trying to connect Smart Mi Humidifier Derma mjjsq, i can't set it up .
In logs I have something like this: 

Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:605
Integration: Wentylator (documentation, issues)
First occurred: 21:47:24 (1 occurrences)
Last logged: 21:47:24

Error while setting up xiaomi_miio_airpurifier platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 605, in async_setup_platform
    from miio import AirHumidifierMjjsq
ImportError: cannot import name 'AirHumidifierMjjsq' from 'miio' (/usr/local/lib/python3.7/site-packages/miio/__init__.py)

Any tips ?
Running RPI4 + docker+hassio on SSD

**Comment by syssi** [comment]
Please update the custom component and try again!
