### ISSUE TITLE
Air Humidifier MJJSQ - not found on reboot

### ISSUE THREAD

**Issue by AlexeyTorch** [syssi/xiaomi_airpurifier#62]
configuration.yaml
```
fan:
  - platform: xiaomi_miio_airpurifier
    host: Here I wrote both IP and DNS devices, no difference
    token: Then I wrote the correct token (working with another automation system)
    name: deerma humidifier
    model: deerma.humidifier.mjjsq
```

In log error:
```
2020-06-02 09:35:54 ERROR (MainThread) [homeassistant.components.fan] Error while setting up xiaomi_miio_airpurifier platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 605, in async_setup_platform
    from miio import AirHumidifierMjjsq
ImportError: cannot import name 'AirHumidifierMjjsq' from 'miio' (/usr/local/lib/python3.7/site-packages/miio/__init__.py)
```

**Comment by syssi** [comment]
It looks like you are using another custom compoent which requires an old/outdated version of python-miio. Please make sure all of your custom components requires the most recent python-miio version (0.5.3).
