### ISSUE TITLE
Error after upgrade new commit

### ISSUE THREAD

**Issue by anhnvme** [syssi/xiaomi_airpurifier#76]
Hello,

After update new commit, 2 device can't work any more
deerma.humidifier.mjjsq and nwt.derh.wdh318efw1

This is error log
```
2020-10-19 01:39:24 ERROR (MainThread) [homeassistant.config] Platform error: fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 814, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 7, in <module>
    from miio import (  # pylint: disable=import-error
ImportError: cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)
2020-10-19 01:39:24 ERROR (MainThread) [homeassistant.config] Platform error: fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 814, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 7, in <module>
    from miio import (  # pylint: disable=import-error
ImportError: cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)
```

Can you help me check it ?

**Comment by syssi** [comment]
My fault. Fixed. Please try again!

**Comment by anhnvme** [comment]
> My fault. Fixed. Please try again!

Hello, it's working now, but still wait For P9. Please update ASAP when miio ready and u have time 

Thanks you

**Comment by anhnvme** [comment]
> My fault. Fixed. Please try again!

Hello,

I just double check again, it's still have trouble at same

**Comment by syssi** [comment]
Did you update the custom component? I've removed the `FanMiot` line to remove the P9 support (temporary). Could you provide the exact error?

**Comment by anhnvme** [comment]
Hello,

Here is error

```
2020-10-19 09:14:50 ERROR (MainThread) [homeassistant.components.fan] Error while setting up xiaomi_miio_airpurifier platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 827, in async_setup_platform
    device = XiaomiAirPurifier(name, air_purifier, model, unique_id)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1053, in __init__
    super().__init__(name, device, model, unique_id)
TypeError: __init__() missing 1 required positional argument: 'retries'
2020-10-19 09:14:50 ERROR (MainThread) [homeassistant.components.fan] Error while setting up xiaomi_miio_airpurifier platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 836, in async_setup_platform
    device = XiaomiAirHumidifierMjjsq(name, air_humidifier, model, unique_id)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1513, in __init__
    super().__init__(name, device, model, unique_id)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1309, in __init__
    super().__init__(name, device, model, unique_id)
TypeError: __init__() missing 1 required positional argument: 'retries'
```
Here is folder of custom component 
![image](https://user-images.githubusercontent.com/13740754/96425757-92730200-1226-11eb-921b-4d539704103a.png)

**Comment by syssi** [comment]
Fixed. Please try again!

**Comment by anhnvme** [comment]
Hello,

It's working now
